import type { Metadata } from "next";
import "./globals.css";
import { Nunito, Syne } from "next/font/google";
import Providers from "./providers/Providers";
import Navbar from "./_components/Navbar";

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
  display: "swap",
});

const syne = Syne({
  subsets: ["latin"],
  variable: "--font-syne",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body
          className={`${nunito.className} ${syne.variable} antialiased flex flex-col max-h-full`}
        >
          <Navbar />
          <main className="container mx-auto p-4 h-full pt-[72px]">
            {children}
          </main>
        </body>
      </html>
    </Providers>
  );
}
